version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies

  pre_build:
    commands:
      - echo Logging in to Docker
      - docker --version

  build:
    commands:
      - echo Building Docker image
      - docker build -t selenium-test .

      - echo Running Selenium tests
      - docker run --name selenium-run selenium-test || true

  post_build:
    commands:
      - echo Copying reports
      - docker cp selenium-run:/app/target ./target || true

artifacts:
  files:
    - target/**/*